//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVEEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BVEEditor.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BVEEditor_FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("BVEEditor_FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_TextNo {
            get {
                return ResourceManager.GetString("CommonStrings_TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not an integer! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_TextNonInteger {
            get {
                return ResourceManager.GetString("CommonStrings_TextNonInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is not a number! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_TextNonNumber {
            get {
                return ResourceManager.GetString("CommonStrings_TextNonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undefined に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_TextUndefined {
            get {
                return ResourceManager.GetString("CommonStrings_TextUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_TextYes {
            get {
                return ResourceManager.GetString("CommonStrings_TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Global_ErrorText {
            get {
                return ResourceManager.GetString("Global_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BVEEditor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_DialogName {
            get {
                return ResourceManager.GetString("MainWindow_DialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_StatusBar_ReadyMessage {
            get {
                return ResourceManager.GetString("MainWindow_StatusBar_ReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy selection to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_EditMenu_Copy_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_EditMenu_Copy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut selection to clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_EditMenu_Cut_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_EditMenu_Cut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_EditMenu_Delete_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_EditMenu_Delete_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste text from clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_EditMenu_Paste_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_EditMenu_Paste_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo last undo action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_EditMenu_Redo_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_EditMenu_Redo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo last action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_EditMenu_Undo_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_EditMenu_Undo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open new buffer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_FileMenu_New_File_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_FileMenu_New_File_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open buffer from disc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_FileMenu_Open_File_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_FileMenu_Open_File_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_FileMenu_Open_Project_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_FileMenu_Open_Project_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save current buffer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_FileMenu_Save_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_FileMenu_Save_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save all buffers currently open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string XML_MainMenu_FileMenu_SaveAll_Description {
            get {
                return ResourceManager.GetString("XML_MainMenu_FileMenu_SaveAll_Description", resourceCulture);
            }
        }
    }
}
