//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVEEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BVEEditor.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All files *.*|* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BVEEditor_FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("BVEEditor_FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Dialogs_Captions_Open {
            get {
                return ResourceManager.GetString("Common_Dialogs_Captions_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save file as... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Dialogs_Captions_Save {
            get {
                return ResourceManager.GetString("Common_Dialogs_Captions_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save before closing? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Dialogs_Captions_SaveBeforeClose {
            get {
                return ResourceManager.GetString("Common_Dialogs_Captions_SaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${0} is modified. Do you want to save it before quitting the application? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Dialogs_Messages_SaveBeforeClose {
            get {
                return ResourceManager.GetString("Common_Dialogs_Messages_SaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ErrorText {
            get {
                return ResourceManager.GetString("Common_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_SearchReplace_MatchCase {
            get {
                return ResourceManager.GetString("Common_SearchReplace_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match whole word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_SearchReplace_MatchWholeWord {
            get {
                return ResourceManager.GetString("Common_SearchReplace_MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search string not found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_SearchReplace_SearchStringNotFound {
            get {
                return ResourceManager.GetString("Common_SearchReplace_SearchStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextCancel {
            get {
                return ResourceManager.GetString("Common_TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextNo {
            get {
                return ResourceManager.GetString("Common_TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${0} is not an integer! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextNonInteger {
            get {
                return ResourceManager.GetString("Common_TextNonInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${0} is not a number! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextNonNumber {
            get {
                return ResourceManager.GetString("Common_TextNonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextOk {
            get {
                return ResourceManager.GetString("Common_TextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undefined に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextUndefined {
            get {
                return ResourceManager.GetString("Common_TextUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextYes {
            get {
                return ResourceManager.GetString("Common_TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Edit {
            get {
                return ResourceManager.GetString("MainMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy selected item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Copy_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Copy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_CopyEntry {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_CopyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut out selected item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Cut_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Cut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_CutEntry {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_CutEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete selected item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Delete_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Delete_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_DeleteEntry {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_DeleteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste item from clipboard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Paste_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Paste_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_PasteEntry {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_PasteEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo last undo action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Redo_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Redo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_RedoEntry {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_RedoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_SelectAllEntry {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_SelectAllEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo last action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Undo_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Undo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_UndoEntry {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_UndoEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_File {
            get {
                return ResourceManager.GetString("MainMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_ApplicationExitEntry {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_ApplicationExitEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_New_File_Description {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_New_File_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_NewEntry {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open a file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_Open_File_Description {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_Open_File_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open a project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_Open_Project_Description {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_Open_Project_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_OpenDocumentEntry {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_OpenDocumentEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_QuickSaveDocumentEntry {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_QuickSaveDocumentEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save current file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_Save_Description {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_Save_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save all the files that are open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_SaveAll_Description {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_SaveAll_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_SaveDocumentAsEntry {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_SaveDocumentAsEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Help {
            get {
                return ResourceManager.GetString("MainMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BVEEditor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_DialogName {
            get {
                return ResourceManager.GetString("MainWindow_DialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ln ${Line} col ${Column} ch ${Character} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_StatusBar_CursorPanelText {
            get {
                return ResourceManager.GetString("MainWindow_StatusBar_CursorPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ready に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_StatusBar_ReadyMessage {
            get {
                return ResourceManager.GetString("MainWindow_StatusBar_ReadyMessage", resourceCulture);
            }
        }
    }
}
