//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVEEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BVEEditor.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   @BVEEditor_FileFilter_AllFiles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BVEEditor_FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("BVEEditor_FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_ErrorText {
            get {
                return ResourceManager.GetString("Common_ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_SearchReplace_MatchCase {
            get {
                return ResourceManager.GetString("Common_SearchReplace_MatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match whole word に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_SearchReplace_MatchWholeWord {
            get {
                return ResourceManager.GetString("Common_SearchReplace_MatchWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search string not found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_SearchReplace_SearchStringNotFound {
            get {
                return ResourceManager.GetString("Common_SearchReplace_SearchStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextCancel {
            get {
                return ResourceManager.GetString("Common_TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @Common_TextNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextNo {
            get {
                return ResourceManager.GetString("Common_TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @Common_TextNonInteger に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextNonInteger {
            get {
                return ResourceManager.GetString("Common_TextNonInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @Common_TextNonNumber に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextNonNumber {
            get {
                return ResourceManager.GetString("Common_TextNonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextOk {
            get {
                return ResourceManager.GetString("Common_TextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @Common_TextUndefined に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextUndefined {
            get {
                return ResourceManager.GetString("Common_TextUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @Common_TextYes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_TextYes {
            get {
                return ResourceManager.GetString("Common_TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_Edit {
            get {
                return ResourceManager.GetString("MainMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_EditMenu_Copy_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Copy_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Copy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_EditMenu_Cut_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Cut_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Cut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_EditMenu_Delete_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Delete_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Delete_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_EditMenu_Paste_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Paste_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Paste_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_EditMenu_Redo_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Redo_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Redo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_EditMenu_Undo_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_EditMenu_Undo_Description {
            get {
                return ResourceManager.GetString("MainMenu_EditMenu_Undo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_File {
            get {
                return ResourceManager.GetString("MainMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_ApplicationExitEntry {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_ApplicationExitEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_FileMenu_NewFile_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_New_File_Description {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_New_File_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_NewEntry {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_FileMenu_OpenFile_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_Open_File_Description {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_Open_File_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_FileMenu_OpenProject_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_Open_Project_Description {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_Open_Project_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_OpenDocumentEntry {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_OpenDocumentEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_FileMenu_Save_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_Save_Description {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_Save_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainMenu_FileMenu_SaveAll_Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenu_FileMenu_SaveAll_Description {
            get {
                return ResourceManager.GetString("MainMenu_FileMenu_SaveAll_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainWindow_DialogName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_DialogName {
            get {
                return ResourceManager.GetString("MainWindow_DialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ln ${Line} col ${Column} ch ${Character} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_StatusBar_CursorPanelText {
            get {
                return ResourceManager.GetString("MainWindow_StatusBar_CursorPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @MainWindow_StatusBar_ReadyMessage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_StatusBar_ReadyMessage {
            get {
                return ResourceManager.GetString("MainWindow_StatusBar_ReadyMessage", resourceCulture);
            }
        }
    }
}
