//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18052
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSharpCode.AvalonEdit.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICSharpCode.AvalonEdit.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Closes the quick search panel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuickSearchPanel_Descriptions_Close {
            get {
                return ResourceManager.GetString("QuickSearchPanel_Descriptions_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finds next match に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuickSearchPanel_Descriptions_FindNext {
            get {
                return ResourceManager.GetString("QuickSearchPanel_Descriptions_FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignores case に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuickSearchPanel_Descriptions_IgnoreCase {
            get {
                return ResourceManager.GetString("QuickSearchPanel_Descriptions_IgnoreCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replaces the currently selected text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuickSearchPanel_Descriptions_Replace {
            get {
                return ResourceManager.GetString("QuickSearchPanel_Descriptions_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replaces all matches texts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuickSearchPanel_Descriptions_ReplaceAll {
            get {
                return ResourceManager.GetString("QuickSearchPanel_Descriptions_ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use regular expression に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuickSearchPanel_Descriptions_UseRegex {
            get {
                return ResourceManager.GetString("QuickSearchPanel_Descriptions_UseRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match against whole words に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string QuickSearchPanel_Descriptions_WholeWords {
            get {
                return ResourceManager.GetString("QuickSearchPanel_Descriptions_WholeWords", resourceCulture);
            }
        }
    }
}
